# -*- coding: utf-8 -*-
"""assingment-1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HjoXB8whKJvBp__TbWQWBSTk00pm5w9c
"""

# task_1 
number_1= int(input('please enter a number: '))
number_2= int(input('please enter a number: '))
print('sum', number_1+number_2)
print('product', number_1*number_2)
print('difference',number_1-number_2)

# task_2
import math
radius= float(input('radius: '))
print('area: ',math.pi*radius**2)
print('circumferance: ',2*math.pi*radius)

# task_3
number_1= int(input('enter a number: '))
number_2= int(input('enter a number: '))
if number_1>number_2:
  print('first number is greater')
elif number_1<number_2:
  print(' second number is greater')
else:
  print('the numbers are equal')

#task_4
a=int(input('please enter a number : '))
b=int(input('please enter a number : '))
if a>b:
  print(a-b)
else: 
  print(b-a)

#task_5
number_1=int(input('please enter a number: '))

if number_1 % 2 == 0 :
  print('even')

else:
  print('odd')

# task_6
number=int(input('please a enter a number : '))

if  number % 2 == 0  or number % 5 == 0  :  
  print(number)
else:
  print('not multiple of 2 or 5')

# task_7
number=int(input('please enter a number: '))

if number%2==0 and number%5==0:
  print('multiple of 2 and 5 both')

elif number%2==0 or number%5==0 :
  print(number)
else:
   
  print('not a multiple we want')

# task_8
number=int(input('please enter a number: '))
if number%2==0 and number%5==0 :
    print(number)

else: 
  print('not a multiple of 2 and 5 both')

# task_9
time_in_second=int(input("enter time in second: "))

hour=time_in_second//3600
remaining_second=time_in_second % 3600
minute=remaining_second//60
second=remaining_second%60



print('hour',hour)
print('minute',minute)
print('second',second)

# task_10
hour=int(input('enter hour on the basis of work:  '))
if hour>168 :
  print('impossible to work more than 168 hours in a week')
elif hour<0 :
  print('hour cannot be negative')


elif hour<=40 :
  print(200*hour)
elif hour>40:
  print(8000+(hour-40)*300)

# task_11
s=int(input('enter the value of "s": '))
if s<100:
  print('l: ',3000-125*s**2)
elif s>=100:
  a=4+s**2/14900
  print('l: ',12000/a)

# task_12
hour=int(input('please enter your time in hour:  '))
if hour<0 or hour>24:
  print('wrong time')
elif hour >= 4 and hour <= 6:
  print('break fast')
elif hour==12 or hour==13:
  print('lunch')
elif hour==16 or hour==17:
  print('snack')
elif hour==19 or hour==20:
  print('dinner')
else:
  print('patience is a virtue')

# task_13
marks=int(input('please enter marks: '))
if marks<0 or marks>100 :
  print('invalid')
elif marks>=90 :
  print('A')
elif marks>=80 : 
  print('B')
elif marks>=70:
  print('C')
elif marks>=60:
  print('D')
elif marks>=50:
 print('E')
else :
  print('F')

# task_14
meter=int(input('please enter in meters: '))
second=int(input('please enter in seconds: '))
kilometer= meter/1000
hour= second/3600
velocity=kilometer/hour
print(velocity ,'Km/h')
if velocity < 60 :
  print('Too slow .Needs more changes.')
elif 60<= velocity >= 90 :
  print('Velocity is ok . The car is ready!')
elif velocity > 90 :
  print('Too fast.Only a few changes should suffice')

# task_15
credit=int(input('please enter the number of credits: '))
CGPA=float(input('enter CGPA: '))
if credit <30:
  print('The student is not eligible for a waiver ')
elif CGPA>=3.80 and CGPA<=3.89  :
  print('The student is eligible for a waiver for 25 percent')

elif CGPA>=3.9 and CGPA <= 3.94:
  print('The student is eligible for a waiver for 50 percent ')

elif CGPA>=3.95 and CGPA<= 3.99:
  print('The student is eligible for a waiver for 75 percent')

elif CGPA==4 :
  print('The student is eligible for a waiver for 100 percent')
else :
    print('The student is not eligible for a waiver')

# task_16
p = 5
q = 6
r = 9
sum = 0
if (p < 12):
  print(r + 2)
else:
  print(r + p)
if (q > 20):
  print(r + 19)
elif (q <= 6):
  print(q + 3)
else:
  print(p + q + r)
if (r > 15):
  print(r)
elif (r == 0):
  print(p + q)
else:
  print(p)
if (sum != 0):
  print(3)
else:
  print(sum + 32)
if (p>0 and r<10):
  print(p+r)
else:
  print(p-r)

# task_17
var1 = var2 = var3 = var4 = var5 = var6 = False
result1 = False
result2 = False
result3 = False
result4 = False
result5 = False
result6 = False
result7 = False
result8 = False
result9 = False
result10 = False
var1 = 4 > 3 - 1
var2 = var1 and False
var3 = True
var4 = False
var5 = True
var6 = var3 and False
result1 = (var1 or var2) and (8 * 10 > 45)
result2 = (var1 or var2) and (result1 and False)
result3 = (var1 and result1) or result2
result4 = (var1 or var2) or ((var3 and var1) and False)
result5 = (var1 and var2) and (result3 or var1)
result6 = ((var3 or var2) and not(result5)) or True
result7 = (var4 and result1) and ((result1 and False) or True)
result8 = ((var1 and result3) and (var5 or var6)) and True
result9 = ((result2 and var2) or (result7 and var1)) and False
result10 = not(var1 and True)
print(result1)
print(result2)
print(result3)
print(result4)
print(result5)
print(result6)
print(result7)
print(result8)
print(result9)
print(result10)

#task_18
var1 = False
var2 = False
var3 = False
var4 = False
var5 = False
var6 = False
result1 = False
result2 = False
result3 = False
result4 = False
result5 = False
result6 = False
result7 = False
result8 = False
result9 = False
result10 = False
var1 = ((not True) or True) and False
var2 = var1 and False
var3 = True and not False
var4 = False
var5 = True
var6 = var3 and False
result1 = (var1 and var2) and (40 % 3) > 45 or (var5 and var6)
result2 = (var1 or var2) or (result1 and False)
result3 = (var1 and result1) or result2 or var5
result4 = (var1 or var2) or ((var3 and var1) and False)
result5 = (var1 and var2) and (result3 or var1)
result6 = ((var3 or (not var2)) and (result5)) or True
result7 = (var4 and result1) and ((result1 and False) or True)
result8 = ((var1 and result3) and ((not var5) or var6)) and True
result9 = ((result2 and var2) or ((not result7) and var1)) and not False
result10 = not(var1 and True)
 

print(result1)
print(result2)
print(result3)
print(result4)
print(result5)
print(result6)
print(result7)
print(result8)
print(result9)
print(result10)

# task_19
var1 = var2 = var3 = var4 = var5 = var6 = False
result1 = result2 = result3 = result4 = result5 = result6 = False
result7 = result8 = result9 = result10 = False
var1 = (not False or False) and True
var2 = var1 and True
var3 = False and not True
var4 = True
var5 = False
var6 = var3 and True
result1 = (var1 and var2) and ( 40 % 3 > 45) or (var5 and var6)
result2 = (var1 or var2) or (result1 and False)
result3 = (var1 and result1) or result2 or var5
result4 = (var1 or var2) or ((var3 and var1) and False)
result5 = (var1 and var2) and (result3 or var1)
result6 = ((var3 or not var2) and (result5)) or True
result7 = (var4 and result1) and ((result1 and False) or True)
result8 = ((var1 and result3) and (not var5 or var6)) and True
result9 = ((result2 and var2) or (not result7 and var1)) and not False
result10 = not (var1 and True)




print(result1)
print(result2)
print(result3)
print(result4)
print(result5)
print(result6)
print(result7)
print(result8)
print(result9)
print(result10)

# task_20
no=int(input('enter a number: '))
if no%2==0 or no%5==0 :
  print('no')
else :
  print(no)

# task_21
no=int(input('enter a number: '))
if no%2==0  and no%5==0 :
  print('no')
else :
  print(no)

# task_22
c_a=int(input())
p_a=int(input())
c_p=c_a*120
p_p=p_a*75
total=c_p+p_p
print('before',total)
if total<300 :
  print('new',total)
elif total>299 and total< 500 :
  print(total-10)
elif total > 499 and total< 750 :
  print(total-20)
elif total>749 and total<1000 :
  print(total-50)
else :
  print(total-150)

# task_23
f=int(input('enter in f: '))
c=(f-32)*0.56
if c<20:
  print('winter')
elif 25>c :
  print('autumn')
elif c<30 :
  print(' spring')
elif c>=30:
  print("summer")
print(c,'degree C')