# -*- coding: utf-8 -*-
"""assingment: 5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fZi6aBXjW-xlWhfu74YC03VQANqG5oGN
"""

exam_marks = {'Cierra Vega': 175, 'Alden Cantrell': 200, 'Kierra Gentry': 165, 'Pierre Cox': 190}
print(exam_marks.get('cerr','sorry its not found'))  #if the key is not found

# task_1
a_tuple = ("The Institute", ("Best Mystery & Thriller", "The Silent Patient", 68821), 75717,
[1, 2, 3, 400, 5, 6, 7], ("Best Fiction", "The Testaments", 98291))
print(a_tuple[3][3])

# task_2
a_tuple=(10, 20, 24, 25, 26, 35, 70)
new_tuple=a_tuple[2:len(a_tuple)-2:1]
print(new_tuple)

# task_3
book_info = (
("Best Mystery & Thriller","The Silent Patient",68,821),
("Best Horror","The Institute",75,717),
("Best History & Biography","The five",31,783 ),
("Best Fiction","The Testaments",98,291)
)
print(f'size of the tuple is : {len(book_info)}')
for i in range(len(book_info)):
  print(book_info[i])

# task_4
book_info = (
("Best Mystery & Thriller","The Silent Patient",68821),
("Best Horror","The Institute",75717),
("Best History & Biography","The five",31783 ),
("Best Fiction","The Testaments",98291)
)
for category,bookname,vote in book_info :
  print(f"{bookname} won the '{category}' category with {vote} votes")

# task_5
given_tuple=(10, 8, 5, 2, 10, 15, 10, 8, 5, 8, 8, 2)
no=int(input())
count=0
for i in given_tuple :
  if no==i :
    count+=1
print(f'{no} appears {count} times in tuple')

# task_6
given_tuple=('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h')
lst=[]
for i in given_tuple :
  lst.append(i)
lst=lst[len(lst)-1::-1]
inverse_tuple=tuple(lst)
print(inverse_tuple)

# task_7
dic_1={'Harry':15, 'Draco':8, 'Nevil':19}
dic_2={'Ginie':18, 'Luna': 14}
dic={}

for key,value in dic_1.items() :
  dic[key]=value
for key,value in dic_2.items():
  dic[key]=value 
print(dic)

# task_8 1st hint
inp=input("enter the dict")
dict={}
sum=0
counter=0
print(inp)
inp=inp[1:-1].split(", ")
print(inp)
for i in inp:
    ky=i.split(":")[0]
    vl=i.split(":")[1]
    dict[ky]=vl
    counter+=1
    sum+=int(vl)
print(f"Average is {int(sum/counter)}.")

# did by myself
inp=input()
inp=inp[1:len(inp)-1].split(', ')
count=0
value=0
for i in inp:
  value+=int(i.split(':')[1])
  count+=1
print(value/count)

# task_8 2nd hint
dic={}
sum=0
counter=0
while True:
    key=input("Enter the key: ")    
    if key=='stop':
        break
    else:
        counter+=1
        value=int(input("Enter the value: "))
        sum+=value
         
        dic[key]=value
print(f"Average is {int(sum/counter)}.")

# task_9
exam_marks = {'Cierra Vega': 175, 'Alden Cantrell': 200, 'Kierra Gentry': 165, 'Pierre Cox': 190}
mark=int(input())
dic={}
for key,value in exam_marks.items():
  if mark<= value :
    dic[key]=value 
print(dic)

# task_10
dic={'sci fi': 5, 'mystery': 3, 'horror': 14, 'young_adult': 2, 'adventure':9}
max=-9999999

for key,value in dic.items() :
  if max<= value :
    max=value 
    book=key
print(f"The highest selling book genre is '{book}' and the number of books sold are {max}.")

# task_11
inp="Python programming is fun".lower()
out={}
for i in inp:
    if i!=" ":
        if i not in out:
            out[i]=1
        else:
            out[i]+=1
print(out)

# by me
inp=input().lower() 
dic={}
for i in inp :
  if i==' ' :
    pass
  elif i not in dic :
    dic[i]=1
  else :
    dic[i]+=1
print(dic)

# task_12
dict_1 = {'A': [1, 2, 3], 'b': ['1', '2'], "c": [4, 5, 6, 7]}
counter=0
for i in dict_1.values():
    for j in i:
        counter+=1
print(counter)

# task_13
list_1 = [("a", 1), ("b", 2), ("a", 3), ("b", 1), ("a", 2), ("c", 1)]
dic={}
for key,value in list_1:
    
    if key not in dic.keys():
      
        dic[key]=[value]
    else:
        dic[key].append(value)
    
print(dic)

# task_14
dict1 = {'a':59 , 'b':-82 , 'c':5 , 'd':-81 , 'e':53}
for i in dict1:
 j = 0
 k = 22
 while j < 5:
  if j % 2 == 0:
    k = dict1[i] + j - (8 + k % 6) / 3
    dict1[i] = dict1[i]+ int(k)
  else:
    k = dict1[i] + j - (6 - k % 8) * 3
    dict1[i] = dict1[i] - int(k)
  j += 1
 print(int(k))
 print(i + " -> " + str(dict1[i]))

# task_15
tup=[(2, 3), (4, 5), (6, 7), (2, 8)]
lst=[]
for key, value in tup :
  lst.append(key*value )
print(lst)

# task_16
tup= ( [1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12])
inp=input()
for i in tup :
  i[len(i)-1]=inp
print(tup)

# task_17

dic= {'c1':'Red', 'c2':'Green', 'c3':None, 'd4':'Blue', 'a5':None}
dic_new={}
for key , value in dic.items():
  if value!=None :
    dic_new[key]=value
print(dic_new)

# task_18
dic = {'a' : 6, 'b' : 7, 'c' : 9, 'd' : 8, 'e' : 11, 'f' : 12, 'g' : 13}
dic_1={}
start=int(input('enter starting limit: '))
end=int(input('enter ending limit(exclusive): '))
for key,value in dic.items() :
  if value>=start and value<end :
    dic_1[key]=value
  
print(dic_1)

# task_19
lst=[(20, 80), (31, 80), (1, 22), (88, 11), (27, 11)]
dict={}
for i in lst:
    if i[1] not in dict.keys():
        dict[i[1]]=[i]
    else:
        dict[i[1]].append(i)
print(dict)

# task_20
sentence=input("Enter a sentence: ").split(" ")
sp_char=input("Enter special characters: ")[1:-1].split(", ")
out={}
sentence_mod=[]
ascii_val=[]
for i in range(len(sentence)):
    if "." in sentence[i]:
        sentence[i]=sentence[i][0:-1]
    if sentence[i] not in sentence_mod:
        sentence_mod.append(sentence[i])
for i in sentence_mod:
    item=0
    for j in i:
        item+=ord(j)
    ascii_val.append(item)
for i in range(len(ascii_val)):
    ascii_val[i]=ascii_val[i]%len(sp_char)
for i in range(len(sentence_mod)):
    if sp_char[ascii_val[i]] not in list(out.keys()):
        out[sp_char[ascii_val[i]]]=[sentence_mod[i]]
    else:
        out[sp_char[ascii_val[i]]].append(sentence_mod[i])
print(out)