# -*- coding: utf-8 -*-
"""assingnment=3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sq5DnPXENR4Z-5cQ4UO7X4Gb2nAQuSQG
"""

#  task_1
s=input("enter Something: ")
print(s[len(s): :-1])

# task_2
s=input("enter Something: ")
num=int(input('enter a number: '))
print(s[num::-1], end='')
print(s[num+1:len(s):1])

# task_3
s=input("enter Something: ")
binary=False
for i in  s:
    if i=='0' or i=='1':
        binary=True
    else:
        binary=False
        print('not a Binary Number')
        break
if binary==True:
    print('a Binary Number')

# task_4
s=input('Enter something: ')
if len(s)<4 or s[len(s)-3::]=='est':
    print(s)
elif s[len(s)-2::]=='er':
    print(s[:len(s)-2:]+'est')
else:
   print(s+'er')

# task_5
inp=input('Enter something: ')
for i in range(len(inp)):
    print(inp[0:i+1])

# task_6
inp=input('Enter something: ')
for i in inp:
    print(i,':',ord(i))

# task_7
s=input('enter something: ')
for i in s:
    if i=='z':
        print('a', end='')
    else:
        print(chr(ord(i)+1), end='')

# task_8
s=input('enter something: ')
for i in range(1,len(s),2):
    if 65<=ord(s[i])<=90:
        print(s[i], end='')
    else:
        print(chr(ord(s[i])-32), end='')

# task_9
s=input('enter something: ')
temp=out=s[0]
for i in s:
    if i!=temp:
        out+=i
    temp=i
print(out)

# by me
inp=input() 
s=inp[0]+''
for i in range(1,len(inp),1) :
  if inp[i]==inp[i-1]:
    pass
  else :
    s=s+inp[i]
print(s)

s=input()
temp=s[0]
out=s[0]
for i in s:
  if i!=temp:
    out=out+i
    temp=i
print(out)

inp=input()
s=''
temp=''

for i in inp :
  if  temp==i:
    pass
  else :
    s+=i
    temp=i
print(s)

# task_10
s=input('enter something: ')
lst=s.split(', ')
str_1=lst[0]
str_2=lst[1]
out=''
if len(str_1) > len(str_2):
    for i in range(len(str_2)):
        out+=str_1[i]+str_2[i]
    out+=str_1[len(str_2):len(str_1)]
else :
    for i in range(len(str_1)):
        out+=str_1[i]+str_2[i]
    out+=str_2[len(str_1):len(str_2)]
print(out)

# task_11
i = 10
while(i >= -20):
  if(i < 0):
     test = " != "
     test = str(i//2) + test + str(int(i/2))
  else:
      test = " == "
      test = str(i//2) + test + str(int(i/2))
  print(test)
  i -= 5

# task_12
test = ""
i = 0
j = 0
k = 15
test = "-->"
while i < 5:
  j = k - 1
  k -= 1
  while j > 10:
    test = str(i + j) + "-->" + test
    print(test)
    j -= 1
  i += 1

# task_13
test = ""
i = 5
j = 0
k = 15
while i< 10:
  k-=1
  j = k
  while j > 10:
    if (j % 2) == 0:
        test = "<--"
        test = str(test) + str(i) + str(2) + "-->" + str(int(j / 2))
    else:
        test = "-->"
        test = "-->" + str(int(i / 2)) + str(test) + str(j)
    print(test)
    j = j-1
  i+=1

# task_14
test = ""
i = 5
j = 0
k = 15
while (i< 10):
  k-=1
  j = k
  while (j > 10 ):
    if j % 2 == 0:
      test = "<--"
      test = test + str( i) + '3' + "-->" + str(j // 3)
    else:
      test = "-->"
      test = "-->" + str((i // 3)) + test + str(j)
    print(test)
    j -=1
  i+=1

i=0
j=0
k=15
test = '<--cat'
while i < 5:
  k -= 1  
  j = k
  while j > 10:
    if j % 2 == 0:
      test += '-->'
      test = test + str(i) + str(j // 2)
    else:
      test += '<--'
      test = test + str(i // 2) + str(j)
    print(test)
    j-=1
  i+=1

# task_16
user=input()
letter=input()
s=''
for i in user :
  if len(user)>3 and letter not in user :
    print(user[1:len(user)-1:1])
  elif i!=letter :
    s=s+i
print(s)

# task_17
user=input()
s=input()
out=''
for i in user:
  if i!=s:
    out+=i
  else:
    print(out)
    out=''
print(out)

user=input()
s=input()
user=user.split(s)

for i in user:
  print(i)

# task_18
user=input()
no=int(input())
if no%2==0 :
  print(user*no*2)
else :
  print(user*no*3)

# task_19
inp=input('Enter something: ')
out=''
count=0
 

for i in inp[0:len(inp)]:
    if i==' ':
        out+=i
         
    elif count%2!=0:
        if 65<=ord(i) and ord(i)<=90:
            out+=chr(ord(i)+32)
        else:
            out+=i
        count+=1
    else:
        if 97<=ord(i) and ord(i)<=122:
            out+=chr(ord(i)-32)
        else:
            out+=i
        count+=1

print(out)