# -*- coding: utf-8 -*-
"""assignment_2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HcUrleJKjV1KbiscrSELmqH8SyFDdzMK
"""

# task_1(a)
no=24
while no >=-6 :
  if no ==-6:
    print(no,end=' ')
  else:
    print(no,end=', ')
  no-=6

# task_1(b)
no=-10
while no<=20 :
  if no==20 :
    print(no,end=" ")
  else :
    print(no,end=', ')
  no+=5

# task_1(c)
no=18
while no<=63 :
  if no==63 :
    print(no,end=" ")
  else :
    print(no, end=', ')
  no+=9

# task_1(d)
no=18
while no<=63 :
  if no%2 ==0:
    print(no, end=', ')
  elif no==63:
    print(-no,end=' ')
  else :
    print(no*(-1),end=', ')
  no+=9

# task_1(d) alternative
no=18
position=0
while no<=63:
  if position%2==0:
    print(no,end=(", "))
  elif no==63 :
    print(-no,end=' ')
  else :
    print(-no,end=',  ')

  no+=9
  position+=1

# task_1d with for 
p=0
for i in range(18,64,9) :
  if p%2==0 :
    print(i,end=', ')
  elif i==63 :
    print(-i, end=' ')
  else :
    print(-i, end=', ')
  p+=1

# task_2
car=input('name of car:  ')
no=int(input('enter a number: '))
counter=1
while counter <= no:
  print(car)
  counter+=1

# task_2 with for 
car=input('enter car name: ')
no=int(input('enter amount: '))
for no in range(1,no+1,1) :
  print(car)

# task_3
no=1
sum=0
while no  <= 600:
  if no % 7 ==0 and no%9==0:
    sum=sum+no
  no+=1
print(sum)

# task_3 for
sum=0
for i in range(1,601,1):

  if i%7==0 and i%9==0 :
    sum=sum+i
print(sum)

# task_4
no=1
sum=0
while no<=600:
  if no%7==0 and no%9==0 :
    sum=sum
  elif no%7==0 or no%9==0 :
    sum=sum+no
  no+=1
print(sum)

# task_4 with for 
sum=0
for i in range(1,601,1):
  if i%7==0 and i%9==0 :
    sum=sum

  elif i%7==0 or i%9==0 :
    sum=sum+i
print(sum)

# task_5
no=10
while no<=50 :
  if no%2==0 :
    no=no
  else :
    print(no,end=' ')
  no+=1

# task_5 for
for i in range(10,51,1) :
  if i%2==0:
    i=i
  else:
    print(i, end='  ')

# task_6
no=int(input('enter a number: '))
num=0
sum=0
while no>=num :
  if no% 2==0 :
    sum=sum-(no**2)
  else :
    sum= sum+(no**2)
  no-=1
print(sum)

# task_6 for  

no=int(input('please enter a number: '))
sum=0
p=0
for i in range(1,no+1,1) :
  if p%2==0 :
    sum=sum+i**2
  else :
    sum=sum-i**2
  p+=1
print(sum)

# task_7 
sum=0
count=0
i=0
while i<10:
  no=int(input('enter a number: '))
  if no%2 !=0 :
    count+=1
    sum+=no
  i+=1
print('the total of odd number :', sum ,' their average: ', sum/count)

# task_7 for
sum=0
count=0
for i in range(0,10,1) :
  no=int(input('enter a number: '))
  if no%2==0 : 
      sum=sum
      
  else: 
    sum=sum+no
    count+=1
    
print('total of odd number: ',sum,'average of odd number: ',sum/count)

# task_8
n= int(input('N='))
sum=0
i=0
while i<=n:
  if i% 7==0:
    sum+=i
  i+=1
print(sum)

# task_8 for
no=int(input('N: '))
sum=0
for i in range(1,no+1,1) :
  if i%7==0 :
    sum=sum+i
  else:
    sum=sum 
print(sum)

# task_9
sum=0
i=0
while i<5 :
  num=int(input('enter a number: '))
  sum+=num
  print(sum)
  i+=1

# task_9 for 
sum=0
for i in range(1,6,1) :
  no=int(input('enter a number: '))
  sum=sum+i
  print(sum)

# task_10
no=int(input('enter a number : '))
while no>0 :
  digit=no%10 
  no= no//10
  if no!=0 :
    print(digit,end=', ')
  else :
    print (digit , end=" ")

#  task_10 problem
no=int(input('enter a number: '))

for i in range(0,here is the problem ,1) :
  digit=no%10
  no=no//10
  if no!=0 :
    print(digit, end=' ,')
  else:
    print(digit, end=' ')

# task_11
no=int(input('enter a number: '))
i=0
while no  >  0 :
  no //= 10
  i+=1
print(i)

# task_12
no= int( input('enter a number: '))
no_1=no
i=0
while no_1>0 :
  no_1 //= 10
  i+=1
print(i)
while no>0 :
  digit = no // 10**(i-1)
  no=no % 10**(i-1)
  if no !=0 :
    print( digit , end =", ")
  else :
     print (digit , end=" ")
  i-=1

# task_12 by me in for
inp=input()
no=int(inp)
for i in range(len(inp)-1,0,-1):
    print(no//10**i,end=',')
    no=no%10**i
print(no)     



# task_13
no=int(input('enter a no: '))
i=1 
divi=0
while i<=no :
  if no%i==0 :
    if no==i :
      print(i)
    else:
      print(i,end=', ')
    divi+=1
  i+=1
print('total',divi,'divisors.')

# task_14
no=int(input('enter a number : '))
i=1 
sum=0
while i<no :
  if no % i ==0 :
    sum+=i
  i+=1
if no==sum:
  print(no, 'is a perfect  number')
else:
  print(no, 'is not a perfect number ')

# task_15
no=int(input('enter a number: '))
divi=0
i=1
while i<=no:
  if no % i ==0:
    divi +=1
  i+=1
if divi==2 :
  print(no,'is a prime number ')
else : 
  print(no, 'is not a prime number')

# task_15
no=int(input())
sum=0


for i in range(1,no,1) :
  if no %i==0:
    sum=sum+i 
if sum==no:
  print('perfect')
else:
  print('not perfect')

# task_16
n=int(input('enter how many number you want: '))
num=int(input('enter first number: '))
max=sum=min=num
for i in range (1,n) :
  num= int(input('enter next number: '))
  sum+=num
  if num> max :
    max=num
  if num < min :
    min = num
print('maximum', max)
print('minimum', min )
print('average', sum/n)

# task_16 from sir
quantity=int(input('no of digit: '))
max=-99999999
min=99999999
sum=0
for i in range(quantity):
  number=int(input("enter a number: "))
  if number>max :
    max=number
  elif number<min :
    min=number 
  sum=sum+number
print('maximum', max)
print('minimum', min )
print('average', sum/quantity)

# task_17
no=int(input('enter a number: '))
for i in range (no) :
  for j in range ( no): 
    print( '+', end =' ')
  print()

# task_18
row=int(input('no of row: '))
col=int(input('no of column: '))
for i in range (row ) :
  for j in range (1,col+1) :
    print(j, end="   ")
  print()

# task_19
n=int(input('enter a number: '))
for i in range (0, n) :
  for j in range (0, i+1) :
    print(j, end='  ')
  print()

# task=20
x = 0
p =0
sum = 0
p = 1
x = 2
q = None
sum = 0
while p < 12:
  q = x + p - (sum + 7 / 3) / 3.0 % 2
  sum = sum + x + int(q)
  x += 1
  print(sum)
  if x > 5:
    p += 4 / 2
  else:
    p += (3 % 1)
sum = int(sum + p)
print(sum)

# task_21
x = 0
p = 0
sum = 0
p = 1
x = 2
q = 0.0
sum = 0
while (p < 10) :
  q = x + p - (sum + int(5 / 3)) / 3.0 % 2
  sum = sum + x + int(q)
  x += 1
  print(sum)
  if (x > 5) :
    p += int(4 / 2)
  else :
    p += 3 % 1
sum = sum + p
print(sum)

# task_22
x = y = 0
sum = 0
while (x < 10):
  y = x - 3
  while (y < 3):
    sum = x - y * 2
    print(sum)
    y = y + 1
  if (x > 7):
    x += 1
  else:
    x += 3
sum = x - y * 2
print(sum)

# task_23
x = 0
y = 0
sum = 0
p = 0.0
while (x < 10):
  y = x // 2  
  while (y < x):
    p = (x + 10.0) / 2
    sum = (sum % 2) + x - y * 2 + int(p)
    print(sum)
    y = y + 2
  if (x > 5):
    x+= 1
  else:
    x += 2

# task_24
test = 1
j = 0
k = 100
while (k > 0):
  while ( j < k ):
    test = k + j -21
    print(str(1 + int (test / 2))+'32')
    j += 10
  k -= 10
test = 1
j = 0
k = 100

# task_25
inp=int(input("Enter Something: "))
first=0
second=1
temp=0
print(first,end=', ')
while second<inp:
    temp=second
    print(second,end=', ')
    second+=first
    first=temp

# task_25
no=int(input())
first=0
second=1
 
print(first,end=' ')
 
while second<no :
  print(second,end=' ')
  temp=second
   
  second=first+second
  first=temp

# task_26
decimal=int(input("Enter Something: "))
binary=''
while decimal!=0:
    binary=str(decimal%2)+binary
    decimal//=2
print(binary)

# task_26 by me
no=int(input())
s=''
while no>0 :
  digit=no%2
  s=s+str(digit)
  no=no//2
k=int(s[len(s)::-1])
print(k)

# task_27
binary=int(input())
i=0
deci=0
while binary>0 :
  digit=binary%10
  binary=binary//10 
  deci=deci+(2**i)*digit 
  i+=1
print(deci)

# task_28
l_range = int(input('Enter lower range: '))
u_range = int(input('Enter upper range: '))
prime=[]
perfect=[]

for i in range(l_range, u_range+1):
    div=0
    sum=0
    for j in range(1,i):
        if i%j==0:
            div+=1
            sum+=j
    if div==1:
        prime.append(i)
    if sum == i:
        perfect.append(i)
    
    
print(f'Between {l_range} and {u_range},')
print(f'Found {len(prime)} prime numbers')
print(f'Found {len(perfect)} perfect numbers')
print('Prime numbers: ', end='')
print (*prime, sep=', ')
print('Perfect number: ', end='')
print (*perfect, sep=', ')

# task_29
l_range = int(input('Enter lower range: '))
u_range = int(input('Enter upper range: '))
check=int(input('Enter a number: '))
product=[]
out=[]
for i in range(l_range, u_range+1):
    digit=1
    while(i>0):
        digit *= i % 10
        i = i // 10
    product.append(digit)
for i in product:
    if i % check==0:
        out.append(i)
print(*out)

start=int(input())
end=int(input())
no=int(input())

for i in range(start,end+1,1):
  digit=i%10
  digit_1=i//10
  if (digit*digit_1)%no==0:
    print(digit*digit_1,end=' ')